version: '3'

tasks:
  build:
    desc: Build the project
    cmds:
      - go build -o bin/scribe ./cmd/scribe

  install:
    desc: Install the project
    cmds:
      - go install ./cmd/scribe

  run:
    desc: Run the application
    cmds:
      - go run ./cmd/scribe

  new:
    desc: Create a new site (usage - task new -- site-name)
    cmds:
      - go run {{.TASKFILE_DIR}}/cmd/scribe new site {{.CLI_ARGS}}
  
  serve:
    desc: Serve a site for development
    cmds:
      - go run {{.TASKFILE_DIR}}/cmd/scribe serve {{.CLI_ARGS}}

  test:
    desc: Run all tests
    cmds:
      - go test ./...

  coverage:
    desc: Generate test coverage
    cmds:
      - mkdir -p build/coverage
      - go test ./... -coverprofile=build/coverage/coverage.out
      - go tool cover -html=build/coverage/coverage.out -o build/coverage/coverage.html
      - go tool cover -func=build/coverage/coverage.out

  lint:
    desc: Run Go linter
    cmds:
      - gofmt -s -w .

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - rm -rf build/
      
  release:
    desc: Create a new release (patch, minor, or major)
    cmds:
      - go run scripts/release.go {{.CLI_ARGS}}
      
  release:patch:
    desc: Create a patch release
    cmds:
      - go run scripts/release.go --type patch
      
  release:minor:
    desc: Create a minor release
    cmds:
      - go run scripts/release.go --type minor
      
  release:major:
    desc: Create a major release
    cmds:
      - go run scripts/release.go --type major
      
  release:dry-run:
    desc: Test the release process without making changes
    cmds:
      - go run scripts/release.go --dry-run