name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          check-latest: true

      # Skip caching since we have no external dependencies

      - name: Run tests
        run: go test ./...

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean --skip-validate
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  homebrew-tap:
    needs: goreleaser
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        id: extract-version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "version_no_v=${VERSION#v}" >> $GITHUB_OUTPUT

      - name: Checkout homebrew tap
        uses: actions/checkout@v3
        with:
          repository: dikaio/homebrew-tap
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-tap

      - name: Update formula
        working-directory: homebrew-tap
        run: |
          VERSION="${{ steps.extract-version.outputs.version }}"
          VERSION_NO_V="${{ steps.extract-version.outputs.version_no_v }}"
          
          # Wait for release to be published and calculate SHA256
          TARBALL_URL="https://github.com/dikaio/scribe/archive/refs/tags/${VERSION}.tar.gz"
          MAX_ATTEMPTS=10
          ATTEMPT=1
          
          while true; do
            echo "Attempt ${ATTEMPT}/${MAX_ATTEMPTS}: Checking if release tarball is available..."
            if curl -s --head --fail "$TARBALL_URL" > /dev/null; then
              echo "Release tarball is available!"
              break
            fi
            
            if [ $ATTEMPT -eq $MAX_ATTEMPTS ]; then
              echo "Release tarball not available after ${MAX_ATTEMPTS} attempts. Exiting."
              exit 1
            fi
            
            ATTEMPT=$((ATTEMPT + 1))
            echo "Waiting 10 seconds before next attempt..."
            sleep 10
          done
          
          # Download and calculate SHA256
          curl -L -o scribe.tar.gz "$TARBALL_URL"
          SHA256=$(sha256sum scribe.tar.gz | awk '{print $1}')
          
          # Update formula file
          sed -i "s|url \".*\"|url \"https://github.com/dikaio/scribe/archive/refs/tags/${VERSION}.tar.gz\"|" Formula/scribe.rb
          sed -i "s|sha256 \".*\"|sha256 \"${SHA256}\"|" Formula/scribe.rb
          
          # Setup git
          git config user.name "GitHub Actions Bot"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          
          # Commit and push
          git add Formula/scribe.rb
          git commit -m "Update scribe to ${VERSION}" || echo "No changes to commit"
          git push