name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.24'
          check-latest: true

      - name: Run tests
        run: go test ./...

      - name: Create .goreleaser.yml if it doesn't exist
        run: |
          if [ ! -f .goreleaser.yml ]; then
            echo "Creating default .goreleaser.yml"
            cat > .goreleaser.yml << 'EOF'
project_name: scribe

before:
  hooks:
    - go mod tidy

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    main: ./cmd/scribe/main.go
    ldflags:
      - -s -w
      - -X github.com/dikaio/scribe/pkg/cli.Version={{.Version}}
      - -X github.com/dikaio/scribe/pkg/cli.Commit={{.Commit}}
      - -X github.com/dikaio/scribe/pkg/cli.Date={{.Date}}
    binary: scribe

archives:
  - format: tar.gz
    name_template: >-
      {{.ProjectName}}_
      {{- .Version}}_
      {{- .Os}}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - 'Merge pull request'
      - 'Merge branch'
EOF
          fi

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  update-homebrew:
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Extract version
        id: extract-version
        run: |
          VERSION=${GITHUB_REF#refs/tags/}
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "version_no_v=${VERSION#v}" >> $GITHUB_OUTPUT
          
      - name: Checkout homebrew-tap repository
        uses: actions/checkout@v3
        with:
          repository: dikaio/homebrew-tap
          token: ${{ secrets.HOMEBREW_TAP_TOKEN }}
          path: homebrew-tap
          
      - name: Download release tarball and calculate SHA256
        run: |
          VERSION=${{ steps.extract-version.outputs.version }}
          TARBALL_URL="https://github.com/dikaio/scribe/archive/refs/tags/${VERSION}.tar.gz"
          
          # Wait for the release to be available (can take a moment after GoReleaser completes)
          for i in {1..10}; do
            echo "Attempt $i: Checking if release tarball is available..."
            if curl -s --head --fail "$TARBALL_URL" > /dev/null; then
              echo "Release tarball is available!"
              break
            fi
            if [ $i -eq 10 ]; then
              echo "Release tarball not available after 10 attempts. Exiting."
              exit 1
            fi
            echo "Waiting 10 seconds before next attempt..."
            sleep 10
          done
          
          # Download and calculate SHA256
          curl -L -o scribe.tar.gz "$TARBALL_URL"
          SHA256=$(sha256sum scribe.tar.gz | awk '{print $1}')
          echo "sha256=${SHA256}" >> $GITHUB_OUTPUT
          
          echo "Version: ${VERSION}"
          echo "SHA256: ${SHA256}"
      
      - name: Update Homebrew Formula
        id: update-formula
        run: |
          VERSION=${{ steps.extract-version.outputs.version }}
          SHA256=$(sha256sum scribe.tar.gz | awk '{print $1}')
          
          # Update the formula
          cd homebrew-tap
          sed -i "s|url \".*\"|url \"https://github.com/dikaio/scribe/archive/refs/tags/${VERSION}.tar.gz\"|" Formula/scribe.rb
          sed -i "s|sha256 \".*\"|sha256 \"${SHA256}\"|" Formula/scribe.rb
          
          # Set Git config
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          
          # Commit and push changes
          git add Formula/scribe.rb
          git commit -m "Update scribe to ${VERSION}"
          git push
          
          echo "Formula updated with version ${VERSION} and SHA256 ${SHA256}"